### ISSUE TITLE
Tornado 4 compatibility

### ISSUE THREAD

**Issue by ijl** [bitly/pynsq#115]
Tornado 4 isn't usable at the moment.

See https://travis-ci.org/bitly/pynsq/jobs/44946872.

```
[nsqd] 2014/12/23 15:47:33.754914 NSQ: persisting topic/channel metadata to nsqd.884.dat
ERROR:nsq.async:uncaught exception in data event
Traceback (most recent call last):
  File "/home/travis/build/bitly/pynsq/nsq/async.py", line 219, in _read_body
    self.trigger(event.DATA, conn=self, data=data)
  File "/home/travis/build/bitly/pynsq/nsq/event.py", line 85, in trigger
    ev(*args, **kwargs)
  File "/home/travis/build/bitly/pynsq/nsq/async.py", line 423, in _on_data
    self.trigger(event.RESPONSE, conn=self, data=data)
  File "/home/travis/build/bitly/pynsq/nsq/event.py", line 85, in trigger
    ev(*args, **kwargs)
  File "/home/travis/build/bitly/pynsq/nsq/async.py", line 385, in _on_response_continue
    self.trigger(event.READY, conn=self)
  File "/home/travis/build/bitly/pynsq/nsq/event.py", line 85, in trigger
    ev(*args, **kwargs)
  File "/home/travis/build/bitly/pynsq/tests/test_reader.py", line 151, in _on_ready
    c.send(nsq.subscribe(topic, 'ch'))
  File "/home/travis/build/bitly/pynsq/nsq/async.py", line 225, in send
    self.stream.write(data)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/tornado/iostream.py", line 1242, in _handle_write
    super(SSLIOStream, self)._handle_write()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/tornado/iostream.py", line 802, in _handle_write
    self._write_buffer_size -= num_bytes
TypeError: unsupported operand type(s) for -=: 'int' and 'NoneType'
[nsqd] 2014/12/23 15:47:38.689345 PROTOCOL(V2): [127.0.0.1:50281] exiting ioloop
[nsqd] 2014/12/23 15:47:38.689432 ERROR: client(127.0.0.1:50281) - failed to read command - EOF
```

**Comment by mpe** [comment]
I had a quick look at fixing this. The quick fix is just to have ```SnappySocket.send()``` and ```DeflateSocket.send()``` return the number of bytes sent.

The complication arises if the underlying ```socket.send()``` only sends some of the data. But AFAICS the code doesn't cope with that now anyway?

**Comment by mreiferson** [comment]
Sounds reasonable, thanks for looking into this.  Want to open a PR (and bump travis to run tests against Tornado 4)?

**Comment by mpe** [comment]
Sure, it's in my branch, waiting for the tests. Will create a PR tomorrow if it's all green.

Another thought is we could use ```socket.sendall()``` to at least try and send all the data?

**Comment by mpe** [comment]
Yeah duh that didn't work. Because _DEFAULT_CA_CERTS is now _default_ca_certs() we'll have to do some version checking muck.

https://travis-ci.org/mpe/pynsq/jobs/55937640

**Comment by jehiah** [comment]
fixed by #124

**Comment by virtuald** [comment]
Can you do a release containing this fix? We're using tornado 4, and would like to use pynsq 0.6.6+. Thanks!

**Comment by mreiferson** [comment]
sure, why not?!?!?
